### ISSUE TITLE
CMaize Documentation link is broken

### ISSUE THREAD

**Issue by zachcran** [CMakePP/cmakepp.github.io#2]
Currently, the CMaize documentation link from https://cmakepp.github.io/ links to https://cmaize.readthedocs.io/en/latest/, which gives a 404 error. There appears to be CMaize documentation living [here](https://cmakepackagingproject.readthedocs.io/en/latest/?badge=latest), though. Is that where it should be pointing instead?

**Comment by ryanmrichard** [comment]
Yeah that's what it should point to.
